export const DIRECTORY_REVIEWED_AT = "2026-08-08";
export const SITE_UPDATED_AT = "2026-08-08";

export type StartupSource = {
  label: string;
  publisher: string;
  url: string;
  supports: string[];
};

export type StartupFounder = {
  name: string;
  alternateNames?: string[];
  role: string;
  linkedin: string;
  connectionSummary: string;
};

export type StartupAccelerator = {
  name: "Y Combinator";
  batch: string;
  profile: string;
};

export type StartupStage = {
  label: string;
  detail: string;
  source: string;
};

export type StartupHiring = {
  status: "Hiring" | "No public openings" | "Unclear";
  detail: string;
  url: string;
};

export type Startup = {
  slug: string;
  name: string;
  alternateNames?: string[];
  logo: string;
  foundedYear: number;
  status: "Active";
  location: string;
  ukrainePresence?: string;
  focus: string;
  sectors: string[];
  tags: string[];
  stage: StartupStage;
  hiring: StartupHiring;
  momentum: string;
  description: string;
  answer: string;
  website: string;
  accelerator?: StartupAccelerator;
  connectionLabel: "Ukrainian-founded" | "Ukraine-connected";
  inclusionReason: string;
  founders: StartupFounder[];
  sources: StartupSource[];
  lastReviewed: string;
};

export const startups: Startup[] = [
  {
    slug: "preply",
    name: "Preply",
    logo: "/logos/preply.png",
    foundedYear: 2012,
    status: "Active",
    location: "New York · London · Kyiv · Barcelona",
    ukrainePresence: "Engineering and company roots in Kyiv",
    focus: "Edtech · Language learning",
    sectors: ["Education", "Marketplace", "Artificial intelligence"],
    tags: ["Unicorn", "$150M Series D", "Global"],
    stage: { label: "Series D", detail: "$150M Series D at a $1.2B valuation, announced in January 2026.", source: "https://www.prnewswire.com/news-releases/preply-raises-150-million-to-shape-the-future-of-education-through-human-led-ai-enhanced-learning-302665890.html" },
    hiring: { status: "Hiring", detail: "Current roles across Kyiv, Barcelona, London, and New York.", url: "https://www.linkedin.com/company/preply/jobs" },
    momentum: "$150M Series D at a $1.2B valuation in January 2026; EBITDA-positive with learners and tutors across 180 countries.",
    description: "A global marketplace for live, AI-enhanced language learning with human tutors.",
    answer: "Preply is a Ukrainian-founded language-learning marketplace that became a unicorn in January 2026 after raising a $150 million Series D led by WestCap at a $1.2 billion valuation.",
    website: "https://preply.com/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Preply’s official history traces the company to founders from Kyiv and an early product and team built in Ukraine. The company maintains a Kyiv engineering presence while operating globally.",
    founders: [
      { name: "Kirill Bigai", alternateNames: ["Kyrylo Bigai"], role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/kirillbigai", connectionSummary: "Ukrainian founder who grew up in Kyiv." },
      { name: "Dmytro Voloshyn", role: "Co-founder and CTO", linkedin: "https://www.linkedin.com/in/dmytrovoloshyn", connectionSummary: "Ukrainian co-founder who helped build Preply’s early team in Kyiv." },
      { name: "Sergey Lukyanov", role: "Co-founder", linkedin: "https://www.linkedin.com/in/sergeylukyanov", connectionSummary: "Ukrainian co-founder of Preply." },
    ],
    sources: [
      { label: "Preply company history", publisher: "Preply", url: "https://preply.com/en/about-us", supports: ["founders", "Ukraine connection", "company history", "global presence"] },
      { label: "Preply raises $150M and becomes a unicorn", publisher: "Preply", url: "https://preply.com/en/blog/preply-raises-150-million-to-shape-the-future-of-education-through-human-led-ai-enhanced-learning/", supports: ["funding", "valuation", "momentum", "product"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "uforce",
    name: "UFORCE",
    logo: "/logos/uforce.png",
    foundedYear: 2025,
    status: "Active",
    location: "London · Washington, D.C. · Ukraine",
    ukrainePresence: "Battlefield-proven Ukrainian systems and engineering",
    focus: "Defense · Autonomous systems",
    sectors: ["Defense", "Autonomy", "Drones", "Robotics"],
    tags: ["Defense", "$1B+ valuation", "UK–Ukraine"],
    stage: { label: "Seed", detail: "$50M seed round co-led by Lakestar and Shield Capital at a valuation above $1B, announced in March 2026.", source: "https://shieldcap.com/newsroom/investing-in-uforce" },
    hiring: { status: "No public openings", detail: "No roles were posted on the company’s public LinkedIn jobs page when checked.", url: "https://www.linkedin.com/company/uforce-global/jobs" },
    momentum: "$50M seed round at a valuation above $1B in March 2026; UFORCE says its systems have completed more than 250,000 missions.",
    description: "Combat-proven autonomous systems spanning sea, air, land, and counter-UAS missions.",
    answer: "UFORCE is a Ukrainian-founded, London-headquartered defense company that raised a $50 million seed round at a valuation above $1 billion in 2026.",
    website: "https://www.uforce.com/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "UFORCE combines Ukrainian battlefield systems and operators with Western manufacturing, capital, and go-to-market leadership. Its board includes former UK Defence Secretary Sir Ben Wallace.",
    founders: [
      { name: "Oleg Rogynskyy", alternateNames: ["Oleh Rohynskyi"], role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/olegrogynskyy", connectionSummary: "Ukrainian-born Silicon Valley entrepreneur and recipient of Ukraine’s Order of Merit." },
      { name: "Oleksiy Honcharuk", role: "Co-founder and Board Chairman", linkedin: "https://www.linkedin.com/in/oleksiy-honcharuk-766776332", connectionSummary: "Former Prime Minister of Ukraine and adviser to Ukraine’s Unmanned Systems Forces." },
    ],
    sources: [
      { label: "UFORCE company and leadership", publisher: "UFORCE", url: "https://www.uforce.com/company", supports: ["company", "founders", "Ukraine connection", "Western ties", "products"] },
      { label: "Shield Capital invests in UFORCE", publisher: "Shield Capital", url: "https://shieldcap.com/newsroom/investing-in-uforce", supports: ["funding", "valuation", "investors"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "quo",
    name: "Quo",
    alternateNames: ["OpenPhone"],
    logo: "/logos/quo.png",
    foundedYear: 2018,
    status: "Active",
    location: "San Francisco",
    focus: "AI · Business communications",
    sectors: ["Artificial intelligence", "SaaS", "Telecommunications"],
    tags: ["YC S18", "$105M financing", "AI"],
    stage: { label: "Growth financing", detail: "$96M go-to-market financing from General Catalyst’s Customer Value Fund plus $9M in equity, announced in September 2025.", source: "https://www.prnewswire.com/news-releases/openphone-becomes-quo-new-name-updated-products-and-105-million-in-growth-financing-mark-major-inflection-point-for-ai-driven-front-office-solution-302562915.html" },
    hiring: { status: "Hiring", detail: "The official careers page is accepting applications for open roles.", url: "https://www.quo.com/careers" },
    momentum: "$105M in growth financing in September 2025 alongside the OpenPhone-to-Quo rebrand and expansion of its Sona AI agent.",
    description: "An AI-powered business phone and front-office platform for small and growing companies.",
    answer: "Quo, formerly OpenPhone, is a San Francisco communications platform co-founded by Kyiv-born entrepreneur Daryna Kulya. It announced $105 million in growth financing in September 2025.",
    website: "https://www.quo.com/",
    accelerator: { name: "Y Combinator", batch: "Summer 2018", profile: "https://www.ycombinator.com/companies/openphone" },
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Co-founder Daryna Kulya was born in Kyiv and later studied and worked in Canada before building Quo in the United States.",
    founders: [
      { name: "Daryna Kulya", role: "Co-founder", linkedin: "https://www.linkedin.com/in/darynakulya", connectionSummary: "Ukrainian-born co-founder from Kyiv." },
      { name: "Mahyar Raissi", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/mahyarr", connectionSummary: "Co-founded Quo with Daryna Kulya and scaled it in the U.S. market." },
    ],
    sources: [
      { label: "OpenPhone becomes Quo and raises $105M", publisher: "Quo", url: "https://www.quo.com/blog/next-chapter/", supports: ["funding", "momentum", "name change", "product"] },
      { label: "Quo company profile", publisher: "Y Combinator", url: "https://www.ycombinator.com/companies/openphone", supports: ["company", "batch", "founders", "location", "status"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "swarmer",
    name: "Swarmer",
    logo: "/logos/swarmer.webp",
    foundedYear: 2023,
    status: "Active",
    location: "Austin · Kyiv",
    ukrainePresence: "Software deployed with nearly 50 Ukrainian units",
    focus: "Defense · Drone swarms",
    sectors: ["Defense", "Autonomy", "Artificial intelligence", "Drones"],
    tags: ["Defense", "Nasdaq: SWMR", "US-backed"],
    stage: { label: "Public · Nasdaq: SWMR", detail: "$17.3M gross IPO completed in March 2026, after a $3.5M Series A-1 financing in January 2026.", source: "https://www.sec.gov/Archives/edgar/data/2092574/000119312526222174/swmr-20260331.htm" },
    hiring: { status: "Hiring", detail: "The official careers board lists current roles in Kyiv, Warsaw, Tallinn, and other locations.", url: "https://jobs.ashbyhq.com/swarmer/" },
    momentum: "Nasdaq listing in March 2026 raised $17.3M gross; the company reports more than 100,000 combat missions and signed a May 2026 agreement with $2.9M in initial fees.",
    description: "Collaborative autonomy software that coordinates large groups of unmanned systems.",
    answer: "Swarmer is a Ukrainian-born drone-autonomy company whose software has supported more than 100,000 combat missions. It listed on Nasdaq in March 2026, raising $17.3 million gross.",
    website: "https://getswarmer.com/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Swarmer’s official history says it was founded in response to Ukrainian battlefield needs. Its software entered combat operations in 2024 and was shaped by continuous deployment with Ukrainian units.",
    founders: [
      { name: "Serhii Kupriienko", role: "Co-founder and Global CEO", linkedin: "https://www.linkedin.com/in/serhii-kupriienko-80383a27", connectionSummary: "Ukraine-based co-founder who led AI and computer-vision teams before Swarmer." },
      { name: "Alex Fink", role: "Co-founder and U.S. CEO", linkedin: "https://www.linkedin.com/in/temuchin43", connectionSummary: "U.S.-based co-founder scaling Swarmer with Western defense partners." },
    ],
    sources: [
      { label: "Swarmer history and leadership", publisher: "Swarmer", url: "https://getswarmer.com/about/", supports: ["founders", "Ukraine connection", "missions", "deployment", "company history"] },
      { label: "Swarmer announces $15M Series A", publisher: "Swarmer", url: "https://www.linkedin.com/posts/getswarmer_swarmer-ukraines-leading-drone-autonomy-activity-7373649376113684480-zcXl", supports: ["funding", "investors", "momentum"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "holywater",
    name: "HOLYWATER TECH",
    alternateNames: ["HOLYWATER"],
    logo: "/logos/holywater.png",
    foundedYear: 2020,
    status: "Active",
    location: "Kyiv",
    ukrainePresence: "Founded and headquartered in Kyiv",
    focus: "Media · AI entertainment",
    sectors: ["Media", "Artificial intelligence", "Consumer", "Entertainment"],
    tags: ["$22M Series A", "Fox partner", "100M+ users"],
    stage: { label: "Series A", detail: "$22M Series A led by Horizon Capital, announced in January 2026.", source: "https://www.holywater.tech/blog/holywater-raises-record-22-million-to-turn-microdramas-into-mainstream-entertainment-in-the-u-s" },
    hiring: { status: "Hiring", detail: "The official site lists current roles across production, engineering, and creative marketing.", url: "https://www.holywater.tech/" },
    momentum: "$22M Series A in January 2026 after roughly doubling 2025 revenue; the company reports more than 100M users and has a 200-series agreement with Fox Entertainment.",
    description: "A mobile-first entertainment platform for vertical series, books, and AI-generated streaming.",
    answer: "HOLYWATER TECH is a Kyiv-founded entertainment technology company that raised a $22 million Series A in 2026 after roughly doubling revenue and expanding its U.S. microdrama partnerships.",
    website: "https://holywater.tech/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "HOLYWATER describes itself as born in Ukraine and maintains its headquarters in Kyiv while building for U.S. and global entertainment markets.",
    founders: [
      { name: "Bogdan Nesvit", role: "Co-founder and Co-CEO", linkedin: "https://www.linkedin.com/in/bogdannesvit", connectionSummary: "Ukrainian co-founder leading HOLYWATER’s global media strategy." },
      { name: "Anatolii Kasianov", role: "Co-founder and Co-CEO", linkedin: "https://www.linkedin.com/in/anatolii-kasianov", connectionSummary: "Ukrainian technical co-founder who built the company’s early product stack." },
    ],
    sources: [
      { label: "HOLYWATER raises $22M", publisher: "HOLYWATER", url: "https://www.holywater.tech/blog/holywater-raises-record-22-million-to-turn-microdramas-into-mainstream-entertainment-in-the-u-s", supports: ["funding", "momentum", "founders", "U.S. expansion"] },
      { label: "HOLYWATER TECH press room", publisher: "HOLYWATER TECH", url: "https://www.holywater.tech/press-room", supports: ["current name", "founders", "Ukraine connection", "users", "company facts"] },
      { label: "HOLYWATER funding and growth", publisher: "Axios", url: "https://www.axios.com/2026/01/15/holywater-microdrama-app-funding", supports: ["Ukraine connection", "funding", "market", "product"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "farsight-vision",
    name: "Farsight Vision",
    logo: "/logos/farsight-vision.png",
    foundedYear: 2023,
    status: "Active",
    location: "Lviv · Tallinn",
    ukrainePresence: "Used by more than 100 Ukrainian defense units",
    focus: "Defense · Geospatial intelligence",
    sectors: ["Defense", "Geospatial", "Drones", "Artificial intelligence"],
    tags: ["Defense", "€7.2M seed", "Estonia–Ukraine"],
    stage: { label: "Seed", detail: "€7.2M seed round led by Axon and SmartCap, with European defense investors participating, announced in February 2026.", source: "https://smartcap.ee/smartcapi-kaitsefond-investeerib-kaitsetehnoloogia-ettevottesse-farsight-vision/" },
    hiring: { status: "Hiring", detail: "The company maintains an active public vacancies portal.", url: "https://farsightvision.hurma.work/public-vacancies?lang=en" },
    momentum: "€7.2M seed in February 2026 led by Axon and SmartCap; the platform serves more than 100 Ukrainian defense and security units and has expanded into NATO markets and Asia.",
    description: "Geospatial intelligence software for drone teams operating in GPS-denied environments.",
    answer: "Farsight Vision is a Ukrainian-Estonian defense startup whose mapping and navigation software is used by more than 100 Ukrainian units. It raised a €7.2 million seed round in 2026.",
    website: "https://fsv.global/en",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Farsight Vision was launched by Ukrainian founders, operates from Lviv and Tallinn, and builds directly with Ukrainian defense and security units.",
    founders: [
      { name: "Viktoriia Yaremchuk", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/viktoriia-yaremchuk-3ba80116", connectionSummary: "Ukrainian co-founder leading the company from its Lviv and Tallinn bases." },
      { name: "Volodymyr Nepiuk", role: "Co-founder and CTO", linkedin: "https://www.linkedin.com/in/vnepyuk", connectionSummary: "Ukrainian technical co-founder building battlefield geospatial tools." },
    ],
    sources: [
      { label: "Farsight Vision company story", publisher: "Farsight Vision", url: "https://fsv.global/en/about-us", supports: ["founders", "Ukraine connection", "locations", "product", "users"] },
      { label: "SmartCap invests in Farsight Vision", publisher: "SmartCap", url: "https://smartcap.ee/smartcapi-kaitsefond-investeerib-kaitsetehnoloogia-ettevottesse-farsight-vision/", supports: ["funding", "Western investors", "momentum"] },
    ],
    lastReviewed: SITE_UPDATED_AT,
  },
  {
    slug: "carmoola",
    name: "Carmoola",
    logo: "/logos/carmoola.png",
    foundedYear: 2021,
    status: "Active",
    location: "London",
    focus: "Fintech · Car finance",
    sectors: ["Fintech", "Consumer finance", "Automotive"],
    tags: ["£300M facility", "UK fintech", "Fast growth"],
    stage: { label: "Series A (extended)", detail: "£15.5M equity extension announced in January 2024, following an £8.5M Series A in February 2023; later financing includes a £300M private ABS facility.", source: "https://www.carmoola.co.uk/blog/carmoola-series-a" },
    hiring: { status: "No public openings", detail: "The official job board listed no openings when checked; Carmoola accepts unsolicited CVs.", url: "https://apply.workable.com/carmoola-1/" },
    momentum: "Up to £300M private ABS facility announced in June 2025, tripling debt capacity as customer numbers doubled year over year.",
    description: "A mobile-first direct lender that simplifies and accelerates UK car financing.",
    answer: "Carmoola is a UK car-finance platform co-founded by Ukrainian engineers Roman Sumnikov and Igor Gordiichuk. It secured a £300 million asset-backed debt facility in 2025.",
    website: "https://www.carmoola.co.uk/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Carmoola was co-founded by Ukrainian engineering leaders Roman Sumnikov and Igor Gordiichuk alongside British founders Aidan and Amy Rushby.",
    founders: [
      { name: "Aidan Rushby", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/aidanrushby", connectionSummary: "British co-founder who built Carmoola with a British-Ukrainian founding team." },
      { name: "Amy Rushby", role: "Co-founder", linkedin: "https://www.linkedin.com/in/amyrushby735", connectionSummary: "British co-founder of Carmoola’s cross-border founding team." },
      { name: "Roman Sumnikov", role: "Co-founder", linkedin: "https://www.linkedin.com/in/rsumnikov", connectionSummary: "Ukrainian engineering co-founder." },
      { name: "Igor Gordiichuk", role: "Co-founder", linkedin: "https://www.linkedin.com/in/igor-gordiichuk", connectionSummary: "Ukrainian engineering co-founder." },
    ],
    sources: [
      { label: "Carmoola secures £300M facility", publisher: "Carmoola", url: "https://www.carmoola.co.uk/news/carmoola-secures-300m-abs-debt-facility", supports: ["financing", "momentum", "Western ties", "growth"] },
      { label: "Carmoola team and milestones", publisher: "Carmoola", url: "https://www.carmoola.co.uk/about-us", supports: ["founders", "company history", "traction", "location"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "earth-ai",
    name: "EARTH AI",
    logo: "/logos/earth-ai.png",
    foundedYear: 2017,
    status: "Active",
    location: "Sydney · Los Angeles",
    focus: "AI · Critical minerals",
    sectors: ["Artificial intelligence", "Mining", "Climate", "Industrial technology"],
    tags: ["YC S19", "$20M Series B", "Critical minerals"],
    stage: { label: "Series B", detail: "$20M Series B led by Tamarack Global and Cantos Ventures, announced in January 2025.", source: "https://www.prnewswire.com/news-releases/earth-ai-closes-oversubscribed-round-raising-20m-for-ai-driven-mineral-exploration-302360289.html" },
    hiring: { status: "Hiring", detail: "Six current roles span geology, AI engineering, geochemistry, drilling, warehouse operations, and finance in Sydney.", url: "https://au.seek.com/Earth-AI-jobs/in-All-Sydney-NSW" },
    momentum: "$20M Series B in January 2025; 2025 reporting added a high-grade indium prospect to earlier palladium, platinum, nickel, and gold discoveries.",
    description: "AI-driven mineral exploration and low-disturbance drilling for critical metal deposits.",
    answer: "EARTH AI is an Australian-U.S. critical-minerals company founded by Ukrainian geologist Roman Teslyuk. It raised a $20 million Series B and announced multiple mineral discoveries in 2025.",
    website: "https://earth-ai.com/",
    accelerator: { name: "Y Combinator", batch: "Summer 2019", profile: "https://www.ycombinator.com/companies/earth-ai" },
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Founder Roman Teslyuk studied geology in Lviv, worked in Ukraine, and represented Ukraine in national and international geology competitions before building EARTH AI abroad.",
    founders: [
      { name: "Roman Teslyuk", role: "Founder and CEO", linkedin: "https://www.linkedin.com/in/roman-teslyuk-a344881a", connectionSummary: "Ukrainian geologist educated at Ivan Franko National University of Lviv." },
    ],
    sources: [
      { label: "EARTH AI raises $20M", publisher: "EARTH AI", url: "https://www.prnewswire.com/news-releases/earth-ai-closes-oversubscribed-round-raising-20m-for-ai-driven-mineral-exploration-302360289.html", supports: ["funding", "momentum", "technology", "founder"] },
      { label: "EARTH AI company profile", publisher: "Y Combinator", url: "https://www.ycombinator.com/companies/earth-ai", supports: ["company", "batch", "founder", "location", "traction"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "infisical",
    name: "Infisical",
    logo: "/logos/infisical.png",
    foundedYear: 2022,
    status: "Active",
    location: "San Francisco",
    focus: "Security · Developer infrastructure",
    sectors: ["Cybersecurity", "Developer tools", "Open source", "Enterprise software"],
    tags: ["YC W23", "$16M Series A", "Open source"],
    stage: { label: "Series A", detail: "$16M Series A led by Elad Gil, announced in June 2025.", source: "https://www.prnewswire.com/news-releases/infisical-secures-16m-series-a-to-redefine-enterprise-secrets-identity-and-access-management-302475063.html" },
    hiring: { status: "Hiring", detail: "Eight open roles across sales, marketing, developer experience, and engineering.", url: "https://infisical.com/careers" },
    momentum: "$16M Series A in June 2025 after reaching cash-flow positivity and enterprise adoption.",
    description: "Open-source security infrastructure for secrets, certificates, and privileged access.",
    answer: "Infisical is a San Francisco security-infrastructure company co-founded by Ukrainian entrepreneur Vlad Matsiiako. It raised a $16 million Series A in 2025 after becoming cash-flow positive.",
    website: "https://infisical.com/",
    accelerator: { name: "Y Combinator", batch: "Winter 2023", profile: "https://www.ycombinator.com/companies/infisical" },
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Co-founder and CEO Vlad Matsiiako publicly identifies as Ukrainian and is building Infisical from Silicon Valley with a global founding team.",
    founders: [
      { name: "Vlad Matsiiako", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/vmatsiiako", connectionSummary: "Ukrainian co-founder building security infrastructure in Silicon Valley." },
      { name: "Tony Dang", alternateNames: ["Tuan Dang"], role: "Co-founder", linkedin: "https://www.linkedin.com/in/tuan-d-a104a6125/", connectionSummary: "Co-founded Infisical with Vlad Matsiiako and Maidul Islam." },
      { name: "Maidul Islam", role: "Co-founder", linkedin: "https://www.linkedin.com/in/maidul98", connectionSummary: "Co-founded Infisical’s open-source security platform." },
    ],
    sources: [
      { label: "Infisical raises $16M Series A", publisher: "Infisical", url: "https://infisical.com/blog/series-a", supports: ["funding", "momentum", "cash-flow status", "customers"] },
      { label: "Infisical company profile", publisher: "Y Combinator", url: "https://www.ycombinator.com/companies/infisical", supports: ["company", "batch", "founders", "location", "team size"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "the-fourth-law",
    name: "The Fourth Law",
    logo: "/logos/the-fourth-law.png",
    foundedYear: 2023,
    status: "Active",
    location: "Kyiv",
    ukrainePresence: "Used by 50+ Ukrainian security and defense units and integrated by 20+ drone manufacturers",
    focus: "Defense · Autonomous targeting",
    sectors: ["Defense", "Autonomy", "Computer vision", "Drones"],
    tags: ["Defense", "NATO-codified", "Axon-backed"],
    stage: { label: "Strategic round", detail: "Undisclosed strategic investment backed by Axon, announced in February 2026; an earlier first round was announced in July 2025 without an amount.", source: "https://www.linkedin.com/posts/yaroslavazhnyuk_great-news-the-fourth-law-has-secured-an-activity-7429098101505748992-MiIU" },
    hiring: { status: "Hiring", detail: "39 current roles across engineering, product, operations, finance, sales, and recruiting.", url: "https://jobs.dou.ua/companies/thefourthlaw-ai/vacancies/" },
    momentum: "Axon-backed strategic investment in February 2026; a June 2026 agreement with RSI Europe targets production of thousands of drones in Lithuania.",
    description: "Autonomy modules and terminal guidance for drones operating through jamming and signal loss.",
    answer: "The Fourth Law is a Ukrainian defense startup building NATO-codified autonomous guidance systems used by more than 50 Ukrainian security and defense units and integrated by more than 20 drone manufacturers.",
    website: "https://thefourthlaw.ai/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "The company was founded in Ukraine by Yaroslav Azhnyuk to solve frontline autonomy needs and develops its systems through a continuous feedback loop with Ukrainian military units.",
    founders: [
      { name: "Yaroslav Azhnyuk", role: "Founder and CEO", linkedin: "https://www.linkedin.com/in/yaroslavazhnyuk", connectionSummary: "Ukrainian serial entrepreneur building autonomous defense systems in Kyiv." },
    ],
    sources: [
      { label: "The Fourth Law company profile", publisher: "The Fourth Law", url: "https://www.linkedin.com/company/thefourthlaw", supports: ["founder", "Ukraine connection", "deployments", "NATO codification", "partners"] },
      { label: "The Fourth Law secures strategic investment", publisher: "Yaroslav Azhnyuk", url: "https://www.linkedin.com/posts/yaroslavazhnyuk_great-news-the-fourth-law-has-secured-an-activity-7429098101505748992-MiIU", supports: ["investment", "Axon partnership", "U.S. expansion", "momentum"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "frontline-robotics",
    name: "Frontline Robotics",
    logo: "/logos/frontline-robotics.png",
    foundedYear: 2023,
    status: "Active",
    location: "Kyiv · Germany",
    ukrainePresence: "Systems used by more than 60 Ukrainian units",
    focus: "Defense · Robotic systems",
    sectors: ["Defense", "Robotics", "Drones", "Manufacturing"],
    tags: ["Defense", "NATO-codified", "German production"],
    stage: { label: "Seed", detail: "$800K seed round closed by July 2025, followed by Quantum Systems acquiring a 10% stake with an option to increase it to 25%; investment amount undisclosed.", source: "https://quantum-systems.com/us/news/quantum-systems-and-frontline-strategic-investment/" },
    hiring: { status: "Hiring", detail: "The official company career page lists current roles.", url: "https://www.frontline-robotics.tech/career" },
    momentum: "Quantum Systems’ strategic investment was followed by a German-Ukrainian joint venture whose German facility targets 10,000 drones for Ukraine within one year.",
    description: "Battlefield-proven robotic and unmanned systems co-produced in Ukraine and Germany.",
    answer: "Frontline Robotics is a Ukrainian defense company whose NATO-codified systems are used by more than 60 units. It formed a German production venture with Quantum Systems in 2026.",
    website: "https://www.frontline-robotics.tech/en",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Frontline Robotics develops systems in direct response to Ukrainian battlefield needs and is transferring combat-proven designs into allied European production.",
    founders: [
      { name: "Yevhenii Tretiak", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/yevhenii-tretiak-943a67ab", connectionSummary: "Ukrainian co-founder scaling battlefield robotics through a German manufacturing partnership." },
      { name: "Pavlo Kosolapkin", role: "Co-founder and CTO", linkedin: "https://www.linkedin.com/in/kosolapkin/", connectionSummary: "Ukrainian technical co-founder of Frontline Robotics." },
      { name: "Oleksii Markhovskyi", role: "Co-founder and CPO", linkedin: "https://www.linkedin.com/in/oleksii-markhovskyi/", connectionSummary: "Ukrainian product and engineering co-founder of Frontline Robotics." },
    ],
    sources: [
      { label: "Quantum Systems invests in Frontline Robotics", publisher: "Quantum Systems", url: "https://quantum-systems.com/us/wp-content/uploads/2025/08/20250716_PR_QS_Frontline-Strategic-Investment_EN.pdf", supports: ["investment", "founder", "Ukraine connection", "products"] },
      { label: "German-Ukrainian production joint venture", publisher: "Quantum Systems", url: "https://quantum-systems.com/wp-content/uploads/2026/02/260213_PR_QFI_Zelenskyy_Final_ENG.pdf", supports: ["Western ties", "production", "capacity", "momentum"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "haiqu",
    name: "Haiqu",
    logo: "/logos/haiqu.png",
    foundedYear: 2022,
    status: "Active",
    location: "New York · London · Lviv · Waterloo",
    ukrainePresence: "Team and office presence in Lviv",
    focus: "Quantum computing · Infrastructure",
    sectors: ["Quantum computing", "Developer tools", "Deep tech"],
    tags: ["$11M seed", "Deep tech", "US–Ukraine"],
    stage: { label: "Seed", detail: "$11M seed round led by Primary Venture Partners, announced in January 2026.", source: "https://0e190a550a8c4c8c4b93-fcd009c875a5577fd4fe2f5b7e3bf4eb.ssl.cf2.rackcdn.com/EINPresswire-882655745-haiqu-raises-11-million-in-seed-round-to-enable-near-term-quantum-use-cases-with-new-operating-system-1.pdf" },
    hiring: { status: "Hiring", detail: "The official job board lists current global roles, including product marketing.", url: "https://apply.workable.com/haiqu-inc/" },
    momentum: "$11M seed in January 2026 led by Primary Venture Partners, with backing from Toyota Ventures and other Western investors.",
    description: "A hardware-aware operating system that makes quantum experiments repeatable and practical.",
    answer: "Haiqu is a U.S.-Ukrainian quantum software company with a team in Lviv. It raised an $11 million seed round in 2026 to bring its quantum operating system to market.",
    website: "https://haiqu.ai/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Haiqu was co-founded by Ukrainian deep-tech entrepreneur Mykola Maksymenko, maintains a Lviv presence, and is publicly recognized as a U.S.-Ukrainian company.",
    founders: [
      { name: "Mykola Maksymenko", role: "Co-founder and CTO", linkedin: "https://www.linkedin.com/in/mykola-maksymenko-4448a839", connectionSummary: "Ukrainian quantum researcher and technology-management leader with roots in Lviv." },
      { name: "Richard Givhan", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/richard-givhan", connectionSummary: "U.S. co-founder scaling Haiqu’s quantum software globally." },
    ],
    sources: [
      { label: "Haiqu raises $11M seed round", publisher: "Haiqu", url: "https://haiqu.ai/insights", supports: ["funding", "investors", "momentum", "product"] },
      { label: "Haiqu team and locations", publisher: "Haiqu", url: "https://haiqu.ai/team", supports: ["founders", "locations", "Lviv presence", "company"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "9-mothers",
    name: "9 Mothers",
    logo: "/logos/9-mothers.png",
    foundedYear: 2024,
    status: "Active",
    location: "Austin, Texas",
    focus: "Defense · Counter-UAS",
    sectors: ["Defense", "Counter-UAS", "Robotics", "Artificial intelligence"],
    tags: ["YC Spring 2026", "Defense", "$1.6M sales"],
    stage: { label: "Venture · amount undisclosed", detail: "Raised venture funding from Streamlined Ventures in June 2026; public amount undisclosed.", source: "https://castleplacement.com/top-10-aerospace-capital-raises-and-investors-in-the-u-s-june-1st-30th-2026/" },
    hiring: { status: "Hiring", detail: "Current Austin roles span perception, robotics, hardware, and embedded systems.", url: "https://9mothers.com/careers" },
    momentum: "$1.6M in reported sales and delivery work for the U.S. Department of War, followed by undisclosed venture funding from Streamlined Ventures in June 2026.",
    description: "Counter-drone systems and AI mission software built for modern defense operations.",
    answer: "9 Mothers is an Austin counter-drone startup with $1.6 million in reported sales and U.S. defense delivery experience. Co-founder Roman Khomenko has documented roots in Ukraine.",
    website: "https://9mothers.com/",
    accelerator: { name: "Y Combinator", batch: "Spring 2026", profile: "https://www.ycombinator.com/companies/9-mothers-corporation" },
    connectionLabel: "Ukraine-connected",
    inclusionReason: "Co-founder Roman Khomenko has documented education and work roots in Ukraine and lists Ukrainian as a native language. The company says its counter-drone mission was motivated by the Russia–Ukraine war.",
    founders: [
      { name: "Roman Khomenko", role: "Co-founder", linkedin: "https://www.linkedin.com/in/dowakin/", connectionSummary: "Studied in Kharkiv, worked in Ukraine, and lists Ukrainian as a native language." },
      { name: "Russell Howard Smith", alternateNames: ["Russell Smith"], role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/russellhowardsmith", connectionSummary: "Austin-based co-founder leading 9 Mothers." },
      { name: "Bogdan Pyzh", role: "Co-founder and COO", linkedin: "https://www.linkedin.com/in/bogdan-pyzh-b5b77388", connectionSummary: "Austin-based co-founder building 9 Mothers’ counter-drone systems." },
    ],
    sources: [
      { label: "9 Mothers company profile", publisher: "Y Combinator", url: "https://www.ycombinator.com/companies/9-mothers-corporation", supports: ["company", "batch", "sales", "location", "product", "founder"] },
      { label: "Roman Khomenko profile", publisher: "LinkedIn", url: "https://www.linkedin.com/in/dowakin/", supports: ["Ukraine connection", "education", "language"] },
    ],
    lastReviewed: SITE_UPDATED_AT,
  },
  {
    slug: "prox",
    name: "Prox",
    logo: "/logos/prox.png",
    foundedYear: 2025,
    status: "Active",
    location: "San Francisco",
    focus: "AI · Technical support",
    sectors: ["Artificial intelligence", "Customer support", "Industrial technology"],
    tags: ["YC Fall 2025", "AI", "Bloomberg Beta"],
    stage: { label: "Early-stage · amount undisclosed", detail: "Raised an undisclosed early-stage round in early 2026.", source: "https://en.ain.ua/2026/05/26/ai-startup-with-ukrainian-roots-prox-got-funding-from-y-combinator/" },
    hiring: { status: "Hiring", detail: "Current roles include engineering, go-to-market, operations, and creative production.", url: "https://www.ycombinator.com/companies/prox/jobs" },
    momentum: "Raised an undisclosed early-stage round in 2026 from Bloomberg Beta, Burst Capital, Weights & Biases, SV Angel, Paul Graham, and AI-company operators; AIN reported $120K annual revenue in May 2026.",
    description: "Multimodal AI support for companies that make complex physical products.",
    answer: "Prox is a Ukrainian-founded AI support company backed in 2026 by Bloomberg Beta, Burst Capital, Weights & Biases, SV Angel, Paul Graham, and AI-company operators.",
    website: "https://useprox.com/",
    accelerator: { name: "Y Combinator", batch: "Fall 2025", profile: "https://www.ycombinator.com/companies/prox" },
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "AIN identifies co-founders Dima Yanovsky and Gregory Makodzeba as Ukrainians and documents the company’s Ukrainian roots.",
    founders: [
      { name: "Dima Yanovsky", alternateNames: ["Dmytro Yanovskyi"], role: "Co-founder", linkedin: "https://www.linkedin.com/in/yanovsk/", connectionSummary: "Identified as Ukrainian in an AIN founder interview." },
      { name: "Gregory Makodzeba", alternateNames: ["Hryhoriy Makodzeba"], role: "Co-founder", linkedin: "https://www.linkedin.com/in/gregory-makodzeba/", connectionSummary: "Identified as Ukrainian in an AIN founder interview." },
    ],
    sources: [
      { label: "Prox company profile", publisher: "Y Combinator", url: "https://www.ycombinator.com/companies/prox", supports: ["company", "batch", "location", "product", "founders"] },
      { label: "Interview with Prox co-founder Dmytro Yanovskyi", publisher: "AIN", url: "https://en.ain.ua/2026/05/26/ai-startup-with-ukrainian-roots-prox-got-funding-from-y-combinator/", supports: ["Ukraine connection", "funding", "Western investors", "founder aliases"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "aisdr",
    name: "AiSDR",
    logo: "/logos/aisdr.png",
    foundedYear: 2023,
    status: "Active",
    location: "San Francisco · Lviv",
    ukrainePresence: "Team presence in Lviv, Ukraine",
    focus: "AI · Sales",
    sectors: ["Artificial intelligence", "Sales technology", "B2B software"],
    tags: ["YC S23", "AI sales", "Lviv team"],
    stage: { label: "Seed", detail: "$3M seed round announced in September 2023; no later publicly disclosed amount is confirmed.", source: "https://jobs.dou.ua/companies/aisdr-inc/" },
    hiring: { status: "No public openings", detail: "The latest public vacancy found was inactive when checked.", url: "https://jobs.dou.ua/companies/aisdr-inc/" },
    momentum: "AiSDR reported 4× revenue growth in 2024, 214% customer growth, and team expansion from 10 to 21.",
    description: "AI sales agents that handle prospecting, follow-ups, and meeting booking.",
    answer: "AiSDR is an AI sales company founded by Ukrainian brothers Yuriy and Oleg Zaremba. The company reported 4× revenue growth and 214% customer growth in 2024.",
    website: "https://aisdr.com/",
    accelerator: { name: "Y Combinator", batch: "Summer 2023", profile: "https://www.ycombinator.com/companies/aisdr" },
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "AIN documents AiSDR as a project founded by Ukrainian brothers Yuriy and Oleg Zaremba, with its team operating from Lviv.",
    founders: [
      { name: "Yuriy Zaremba", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/yuriy-zaremba", connectionSummary: "Ukrainian co-founder building AiSDR from Lviv." },
      { name: "Oleg Zaremba", role: "Co-founder", linkedin: "https://www.linkedin.com/in/oleg-zaremba", connectionSummary: "Ukrainian co-founder building AiSDR from Lviv." },
    ],
    sources: [
      { label: "AiSDR company profile", publisher: "Y Combinator", url: "https://www.ycombinator.com/companies/aisdr", supports: ["company", "batch", "location", "product", "founders"] },
      { label: "Interview with AiSDR co-founder Yuriy Zaremba", publisher: "AIN", url: "https://en.ain.ua/2024/02/13/interview-with-yuriy-zaremba-from-aisdr/", supports: ["Ukraine connection", "Lviv presence", "company background", "funding"] },
      { label: "AiSDR 2024 year in review", publisher: "AiSDR", url: "https://aisdr.com/blog/aisdr-2024-year-in-review/", supports: ["revenue growth", "team growth", "product momentum"] },
    ],
    lastReviewed: SITE_UPDATED_AT,
  },
  {
    slug: "sparkles",
    name: "Sparkles",
    logo: "/logos/sparkles.png",
    foundedYear: 2025,
    status: "Active",
    location: "San Francisco",
    focus: "AI · Developer tools",
    sectors: ["Artificial intelligence", "Developer tools", "Collaboration software"],
    tags: ["YC Winter 2026", "AI", "Developer tools"],
    stage: { label: "Stage undisclosed", detail: "$3.5M total raised; round date and formal stage were not separately disclosed.", source: "https://www.ycombinator.com/companies/sparkles/jobs" },
    hiring: { status: "Hiring", detail: "Hiring a founding product engineer in San Francisco.", url: "https://www.ycombinator.com/companies/sparkles/jobs" },
    momentum: "Raised $3.5M and is hiring a founding product engineer after launching in Y Combinator’s Winter 2026 batch.",
    description: "An AI workspace that helps teams safely make changes to existing codebases.",
    answer: "Sparkles is a San Francisco developer-tools startup founded by Ukrainian entrepreneur Ai Daniil Bekirov. It raised $3.5 million and is hiring after launching in Y Combinator’s Winter 2026 batch.",
    website: "https://sparkles.dev/",
    accelerator: { name: "Y Combinator", batch: "Winter 2026", profile: "https://www.ycombinator.com/companies/sparkles" },
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Founder Daniil Bekirov self-identifies with Ukraine in his official Y Combinator founder biography.",
    founders: [
      {
        name: "Ai Daniil Bekirov",
        alternateNames: ["Daniil Bekirov"],
        role: "Founder",
        linkedin: "https://www.linkedin.com/in/aidaniilbekirov",
        connectionSummary: "Self-identifies with Ukraine in his official Y Combinator founder biography.",
      },
    ],
    sources: [
      {
        label: "Sparkles company and founder profile",
        publisher: "Y Combinator",
        url: "https://www.ycombinator.com/companies/sparkles",
        supports: ["company", "batch", "founded year", "location", "product", "founder", "Ukraine connection"],
      },
    ],
    lastReviewed: SITE_UPDATED_AT,
  },
  {
    slug: "headway-inc",
    name: "Headway Inc",
    logo: "/logos/headway-inc.png",
    foundedYear: 2019,
    status: "Active",
    location: "Kyiv · Madrid · Limassol · Warsaw · Lviv",
    ukrainePresence: "Founded in Kyiv with offices in Kyiv and Lviv",
    focus: "Edtech · Lifelong learning",
    sectors: ["Education", "Artificial intelligence", "Consumer software"],
    tags: ["Strategic round", "150M+ users", "Global"],
    stage: { label: "Strategic round", detail: "First external institutional round, led by Bullhound Capital and announced in September 2025; amount undisclosed.", source: "https://bullhoundcapital.com/press/bullhound-capital-invests-in-learning-platform-headway-inc/" },
    hiring: { status: "Hiring", detail: "Current roles across Kyiv, Madrid, Lviv, Limassol, and remote locations.", url: "https://careers.headway.inc/jobs" },
    momentum: "Raised its first external institutional round in 2025; Endeavor reports more than 150M users across 170+ countries.",
    description: "Consumer learning products built around short-form books, courses, and daily practice.",
    answer: "Headway Inc is a Ukrainian-founded learning company with more than 150 million users across its products. It raised its first external institutional round in 2025.",
    website: "https://www.headway.inc/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Ukrainian entrepreneur Anton Pavlovsky founded Headway in Kyiv and continues to operate offices in Kyiv and Lviv.",
    founders: [
      { name: "Anton Pavlovsky", alternateNames: ["Anton Pavlovskyi"], role: "Founder and CEO", linkedin: "https://www.linkedin.com/in/anton-pavlovskyi", connectionSummary: "Ukrainian entrepreneur who founded Headway in Kyiv." },
    ],
    sources: [
      { label: "Bullhound Capital invests in Headway", publisher: "Bullhound Capital", url: "https://bullhoundcapital.com/press/bullhound-capital-invests-in-learning-platform-headway-inc/", supports: ["investment", "company", "product", "momentum"] },
      { label: "How Anton Pavlovsky built Headway", publisher: "Forbes", url: "https://www.forbes.com/sites/martinadilicosa/2025/10/17/how-ukrainian-entrepreneur-anton-pavlovsky-built-edtech-app-headway-into-a-global-phenomenon/", supports: ["founder", "Ukraine connection", "company history"] },
      { label: "Headway joins Endeavor", publisher: "Endeavor Ukraine", url: "https://www.linkedin.com/posts/endeavor-ukraine_headway-inc-the-ukraine-born-company-that-activity-7349410121942204416-46Mw", supports: ["users", "countries", "Ukraine connection"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "fintech-it-group",
    name: "Fintech-IT Group",
    alternateNames: ["Fintech Band", "mono"],
    logo: "/logos/fintech-it-group.png",
    foundedYear: 2017,
    status: "Active",
    location: "Kyiv · Dnipro",
    ukrainePresence: "Founded and operated in Ukraine",
    focus: "Fintech · Digital banking",
    sectors: ["Fintech", "Banking software", "E-commerce"],
    tags: ["$1B valuation", "10M users", "US-backed"],
    stage: { label: "Growth equity", detail: "UMAEF and private U.S. investors completed an undisclosed investment at a $1B valuation in October 2025.", source: "https://umaef.org/wp-content/uploads/2025/10/umaef_press-release_fintech_en_vf.pdf" },
    hiring: { status: "Hiring", detail: "Current roles in software engineering, data, AI, and B2B sales.", url: "https://jobs.dou.ua/companies/mono/vacancies/" },
    momentum: "Reached a $1B valuation in 2025; the company reports 10M monobank users and 6.4M monomarket purchases.",
    description: "The product company behind monobank and the monomarket commerce platform.",
    answer: "Fintech-IT Group is the Ukrainian product company behind monobank. A U.S.-backed investment valued it at $1 billion in 2025.",
    website: "https://fintechitgroup.com/en/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Oleg Gorokhovskyi and Mykhailo Rogalskyi founded the company in Ukraine and built monobank for the Ukrainian market.",
    founders: [
      { name: "Oleg Gorokhovskyi", role: "Co-founder", linkedin: "https://www.linkedin.com/in/oleg-gorokhovskyi-bb484a173", connectionSummary: "Ukrainian co-founder of Fintech-IT Group and monobank." },
      { name: "Mykhailo Rogalskyi", alternateNames: ["Misha Rogalskyi"], role: "Co-founder", linkedin: "https://www.linkedin.com/in/rogalskiy", connectionSummary: "Ukrainian co-founder of Fintech-IT Group and monobank." },
    ],
    sources: [
      { label: "UMAEF invests in Fintech-IT Group", publisher: "Ukraine-Moldova American Enterprise Fund", url: "https://umaef.org/wp-content/uploads/2025/10/umaef_press-release_fintech_en_vf.pdf", supports: ["investment", "valuation", "founders", "users", "Ukraine connection"] },
      { label: "Fintech-IT Group company profile", publisher: "Fintech-IT Group", url: "https://fintechitgroup.com/en/", supports: ["founders", "products", "users", "company"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "banani-ai",
    name: "Banani AI",
    logo: "/logos/banani-ai.png",
    foundedYear: 2024,
    status: "Active",
    location: "Berlin · Kyiv",
    focus: "AI · Product design",
    sectors: ["Artificial intelligence", "Design tools", "Developer tools"],
    tags: ["€850K pre-seed", "200K+ users", "Berlin–Kyiv"],
    stage: { label: "Pre-seed", detail: "€850K round from Specialist VC and Inovo VC, with angels from Canva and WhatsApp, announced in May 2025.", source: "https://scroll.media/en/2025/05/20/banani-ai-founded-by-ukrainians-raises-e850000/" },
    hiring: { status: "Hiring", detail: "The official careers page lists a founding engineer role in Berlin.", url: "https://www.banani.co/company/careers" },
    momentum: "Raised €850K in 2025 and reports more than 200,000 users.",
    description: "An AI product-design tool that turns prompts, images, and product requirements into editable interfaces.",
    answer: "Banani AI is a Ukrainian-founded design tool based in Berlin and Kyiv. It raised an €850,000 pre-seed round in 2025 and reports more than 200,000 users.",
    website: "https://www.banani.co/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Vlad Solomakha and Vova Parkhomchuk are Ukrainian founders building Banani from Berlin and Kyiv.",
    founders: [
      { name: "Vlad Solomakha", role: "Co-founder", linkedin: "https://www.linkedin.com/in/vpznc", connectionSummary: "Ukrainian co-founder of Banani AI." },
      { name: "Vova Parkhomchuk", role: "Co-founder", linkedin: "https://www.linkedin.com/in/vova-parkhomchuk-6aa105141", connectionSummary: "Ukrainian co-founder of Banani AI." },
    ],
    sources: [
      { label: "About Banani", publisher: "Banani AI", url: "https://www.banani.co/company/about", supports: ["founders", "Ukraine connection", "company", "product"] },
      { label: "Banani raises €850K", publisher: "Scroll", url: "https://scroll.media/en/2025/05/20/banani-ai-founded-by-ukrainians-raises-e850000/", supports: ["funding", "investors", "founders", "users"] },
      { label: "Banani founder updates", publisher: "Banani AI", url: "https://www.banani.co/blog/author/vlad-solomakha", supports: ["users", "momentum"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "zeely-ai",
    name: "Zeely AI",
    alternateNames: ["Zeely", "Zeely – AI Admaker"],
    logo: "/logos/zeely-ai.png",
    foundedYear: 2022,
    status: "Active",
    location: "Kyiv · Warsaw · Remote",
    ukrainePresence: "Founded in Ukraine with a team in Kyiv",
    focus: "AI · Advertising",
    sectors: ["Artificial intelligence", "Marketing technology", "SaaS"],
    tags: ["Seed", "1.5M+ businesses", "6× growth"],
    stage: { label: "Seed", detail: "$1M seed round raised in 2023; Deel committed a further $1M investment after Zeely won The Pitch in May 2026, with final terms pending in July.", source: "https://en.ain.ua/2026/07/24/the-higher-the-algorithms-accuracy-the-more-autonomous-the-process-the-team-of-ukrainian-startup-zeely-on-investment-and-the-new-phase-of-zeely-20/" },
    hiring: { status: "Hiring", detail: "Current roles across product, engineering, data, marketing, operations, and recruiting.", url: "https://jobs.dou.ua/companies/zeely-ai/vacancies/" },
    momentum: "Reported 6× year-over-year growth and more than 1.5M businesses using the product; won a $1M investment commitment in 2026.",
    description: "AI software for creating ads, launching campaigns, and analyzing performance.",
    answer: "Zeely AI is a Ukrainian-founded marketing platform used by more than 1.5 million businesses. It reported 6× year-over-year growth in 2026.",
    website: "https://zeely.ai/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Dima Samoiliuk, Yaroslav Samoiliuk, and Alina Bondarenko founded Zeely in Ukraine and continue to operate a Kyiv team.",
    founders: [
      { name: "Dima Samoiliuk", alternateNames: ["Dmytro Samoiliuk"], role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/samoiliuk", connectionSummary: "Ukrainian co-founder and CEO of Zeely AI." },
      { name: "Yaroslav Samoiliuk", role: "Co-founder and COO", linkedin: "https://www.linkedin.com/in/yaroslavsam", connectionSummary: "Ukrainian co-founder and COO of Zeely AI." },
      { name: "Alina Bondarenko", role: "Co-founder and CCO", linkedin: "https://www.linkedin.com/in/bondarenko-alina", connectionSummary: "Ukrainian co-founder and CCO of Zeely AI." },
    ],
    sources: [
      { label: "Zeely leadership", publisher: "Zeely AI", url: "https://zeely.ai/leadership", supports: ["founders", "company history", "Ukraine connection"] },
      { label: "Zeely on its investment and growth", publisher: "AIN", url: "https://en.ain.ua/2026/07/24/the-higher-the-algorithms-accuracy-the-more-autonomous-the-process-the-team-of-ukrainian-startup-zeely-on-investment-and-the-new-phase-of-zeely-20/", supports: ["stage", "investment", "growth", "users", "hiring"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "tencore",
    name: "TENCORE",
    logo: "/logos/tencore.png",
    foundedYear: 2024,
    status: "Active",
    location: "Kyiv · Germany",
    ukrainePresence: "Designed and manufactured in Ukraine for Ukrainian defense units",
    focus: "Defense · Ground robotics",
    sectors: ["Defense", "Robotics", "Autonomy", "Manufacturing"],
    tags: ["Defense", "$3.74M seed", "German production"],
    stage: { label: "Seed", detail: "$3.74M seed investment from U.S.-Ukrainian MITS Capital, announced in July 2025.", source: "https://thedigital.gov.ua/news/business/amerikanski-investitsii-v-ukrainsku-oboronu-tencore-zaluchila-mayzhe-4-mln-cherez-diyacity" },
    hiring: { status: "Hiring", detail: "Current public openings include project management roles in Ukraine.", url: "https://www.linkedin.com/jobs/view/4375293940/" },
    momentum: "Produced and deployed more than 800 TerMIT ground robots, then formed a German production joint venture with Quantum Systems.",
    description: "Modular unmanned ground vehicles for logistics, evacuation, engineering, and combat missions.",
    answer: "TENCORE is a Ukrainian defense company manufacturing the TerMIT ground robot. It raised $3.74 million in 2025 and formed a German production venture with Quantum Systems.",
    website: "https://tencore.com.ua/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Ukrainian founders Maksym Vasylchenko and Roman Tkachenko built TENCORE in Kyiv for frontline ground-robotics requirements.",
    founders: [
      { name: "Maksym Vasylchenko", role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/maksym-vasylchenko-607409aa/", connectionSummary: "Ukrainian co-founder and CEO of TENCORE." },
      { name: "Roman Tkachenko", role: "Co-founder and CBDO", linkedin: "https://www.linkedin.com/in/roman-tkachenko-ua/", connectionSummary: "Ukrainian co-founder leading business development at TENCORE." },
    ],
    sources: [
      { label: "TENCORE raises $3.74M", publisher: "Ministry of Digital Transformation of Ukraine", url: "https://thedigital.gov.ua/news/business/amerikanski-investitsii-v-ukrainsku-oboronu-tencore-zaluchila-mayzhe-4-mln-cherez-diyacity", supports: ["funding", "investor", "Ukraine connection", "company"] },
      { label: "Quantum Systems and TENCORE form German joint venture", publisher: "Quantum Systems", url: "https://www.quantum-systems.com/en/press/quantum-systems-and-tencore-establish-joint-venture-for-ugv-production-in-germany", supports: ["production", "Western ties", "product", "momentum"] },
      { label: "TENCORE company profile", publisher: "TENCORE", url: "https://www.linkedin.com/company/tencore-llc", supports: ["founders", "deployments", "orders", "company"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
  {
    slug: "norda-dynamics",
    name: "NORDA Dynamics",
    logo: "/logos/norda-dynamics.png",
    foundedYear: 2023,
    status: "Active",
    location: "Lviv",
    ukrainePresence: "Founded and operated in Lviv for Ukrainian defense units",
    focus: "Defense · Autonomous navigation",
    sectors: ["Defense", "Autonomy", "Drones", "Computer vision"],
    tags: ["Defense", "$1M seed", "Sweden–Ukraine"],
    stage: { label: "Seed", detail: "$1M round led by Sweden's Varangians, with Ukrainian and U.S. investors, announced in September 2025.", source: "https://thedefender.media/en/2025/09/norda-dynamics-raises-1-mln/" },
    hiring: { status: "Hiring", detail: "Current openings span machine learning, edge systems, integration, support, and sales.", url: "https://www.linkedin.com/posts/norda-dynamics_%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0-norda-dynamics-%D0%B4%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F-%D0%B4%D0%BE-talent-activity-7437799620933693441-jqhd" },
    momentum: "Reports more than 62,000 combat missions completed in 2025, with 250+ crews using its systems and integrations across Ukrainian drone manufacturers.",
    description: "Autonomous UAV navigation and terminal guidance that operate without GPS or a live communications link.",
    answer: "NORDA Dynamics is a Lviv defense startup building autonomous drone navigation for electronic-warfare conditions. It raised a $1 million seed round led by Swedish investors in 2025.",
    website: "https://www.norda.tech/",
    connectionLabel: "Ukrainian-founded",
    inclusionReason: "Ukrainian founder Nazar Bigun started NORDA Dynamics in Lviv to build autonomous navigation for Ukrainian drone units.",
    founders: [
      { name: "Nazar Bigun", alternateNames: ["Nazar Bihun"], role: "Co-founder and CEO", linkedin: "https://www.linkedin.com/in/nazar-bigun-2ba982134/", connectionSummary: "Ukrainian co-founder and CEO of NORDA Dynamics." },
      { name: "Gauthier Vasseur", role: "Co-founder", linkedin: "https://www.linkedin.com/in/gauthiervasseur/", connectionSummary: "French co-founder supporting NORDA's international development." },
    ],
    sources: [
      { label: "NORDA Dynamics raises $1M", publisher: "The Defender", url: "https://thedefender.media/en/2025/09/norda-dynamics-raises-1-mln/", supports: ["funding", "investors", "company", "Ukraine connection"] },
      { label: "NORDA Dynamics company profile", publisher: "NORDA Dynamics", url: "https://www.linkedin.com/company/norda-dynamics", supports: ["company", "location", "product", "deployments", "founders"] },
      { label: "NORDA founder announcement", publisher: "Nazar Bigun", url: "https://www.linkedin.com/posts/nazar-bigun-2ba982134_norda-dynamics-%D0%B1%D1%83%D0%BB%D0%B8-%D0%B2%D1%96%D0%B4%D1%96%D0%B1%D1%80%D0%B0%D0%BD%D1%96-%D1%81%D0%BF%D0%BE%D0%BC%D1%96%D0%B6-%D0%BD%D0%B0%D0%B9%D0%BA%D1%80%D0%B0%D1%89%D0%B8%D1%85-activity-7285608843290505216-po9l", supports: ["founders", "international program", "Western ties"] },
    ],
    lastReviewed: DIRECTORY_REVIEWED_AT,
  },
];

export function getStartup(slug: string) {
  return startups.find((startup) => startup.slug === slug);
}
